CREATE DATABASE IF NOT EXISTS MW_DATABASE;
USE MW_DATABASE;

CREATE TABLE MW_DATABASE.MW_TABLE (
	id BIGINT,
	userId BIGINT,
	title VARCHAR(255),
	body VARCHAR(2047),
	deleted BOOLEAN NOT NULL DEFAULT FALSE,
	edited BOOLEAN NOT NULL DEFAULT FALSE
)
ENGINE=InnoDB
COMMENT='Michal Wojtanis';
